services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgres/log
    networks:
      - app-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    depends_on:
      - db
    env_file: ./.env
    environment:
      PORT: ${PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_URL: ${DATABASE_URL}
    ports: 
      - "${PORT}:${PORT}"
    networks:
      - app-network
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    env_file: ./.env
    environment:
      VITE_BACK: ${VITE_BACK}
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

volumes:
  pgdata:
  pglogs:

networks:
  app-network:
    driver: bridge
